# Generated by Django 4.1.7 on 2024-02-05 00:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_create_track"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ActivityLog",
        ),
    ]
