# Generated by Django 4.2.13 on 2024-06-04 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_delete_activitylog"),
    ]

    operations = [
        migrations.CreateModel(
            name="Circuit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=512)),
                ("start_line", models.JSONField()),
            ],
        ),
        migrations.RenameField(
            model_name="track",
            old_name="done",
            new_name="finished",
        ),
        migrations.AddField(
            model_name="track",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="track",
            name="started",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Point",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("turn", models.IntegerField()),
                ("point_data", models.JSONField(default={})),
                ("created_at_local", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points",
                        to="core.track",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="track",
            name="circuit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.circuit",
            ),
        ),
    ]
