# Generated by Django 4.2.13 on 2024-06-09 22:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_circuit_rename_done_track_finished_track_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="circuit",
            name="start_line",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="point",
            name="point_data",
            field=models.JSONField(default=dict),
        ),
    ]
