# Generated by Django 4.2.13 on 2024-06-22 00:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_circuit_start_line_alter_point_point_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="point",
            name="ignored",
            field=models.BooleanField(default=False),
        ),
    ]
